FROM achwie/alpine-java:0.2

LABEL author="Achim Wiedemann"
LABEL description="Kafka Demo App - Frontend Service"

ADD dockerfiles/frontend-service.jar /

CMD ["java", "-jar", "/frontend-service.jar"] 

